Repository vuematerial/vue-material, pull requests merged in 2020-08, with the labels that each got.

#2165 Update GettingStarted.vue
  docs/app/pages/GettingStarted.vue
Labels: in progress, in review, ready for merge

#2075 Fix selection when value is empty string
  src/components/MdField/MdSelect/MdOption.vue
Labels: C: MdSelect, in review, ready for merge, will be approved

#2203 Fixed docs position and height
  docs/app/template/MainNav.vue
Labels: documentation, in review, ready for merge

#2108 Fixing the label for inputs when we received an invalid value
  src/components/MdField/MdField.vue
  src/components/MdField/MdFieldMixin.js
Labels: bug, in review, ready for merge

#2078 fix(MdDatepicker): Pick text button (confirm and cancel) from locale configuration
  docs/app/pages/Configuration.vue
  package.json
  src/components/MdDatepicker/MdDatepickerDialog.vue
  src/material.js
  test/setup.js
  yarn.lock
Labels: C: MdDatepicker, in review, ready for merge, will be approved
